### ISSUE TITLE
wrong redirect

### ISSUE THREAD

**Issue by njordr** [lejmr/iredmail-docker#2] opened 2017-06-05 13:39 UTC
Hi.

This is the main page after a fresh install:

![image](https://cloud.githubusercontent.com/assets/4282925/26785974/2692d5fc-4a05-11e7-9809-35fbb48890d0.png)

Any advice?

Thanks

**Comment by lejmr** [comment] 2017-10-01 14:03
Which version is this impacted? Can you please post whole command which you used for starting the container? 

Cheers

**Comment by agilob** [comment] 2017-10-07 17:45
I had the same issue for a moment, it's just your nginx proxy_pass that's invalid.

I started the docker instance with port mapping:
```
docker run --privileged -p 8666:80 -p 8443:443 
```

There is relevant configuration for you:
```
upstream iredMailHttp {
  server 127.0.0.1:8666;
}

upstream iredMailHttpS {
  server 127.0.0.1:8443;
}

server {
  server_name emaildomain
  listen 80;
  listen [::]:80;
  
  location / {
   proxy_pass http://iredMailHttp/;
   proxy_set_header    Host            $host;
   proxy_set_header    X-Real-IP       $remote_addr;
   proxy_set_header    X-Forwarded-for $remote_addr;
  }
}

server {
  server_name emaildomain;
  listen 443 http2 ssl;
  listen [::]:443 http2 ssl; 

  location / {
    proxy_pass https://iredMailHttpS/;
    proxy_set_header    Host            $host;
    proxy_set_header    X-Real-IP       $remote_addr;
    proxy_set_header    X-Forwarded-for $remote_addr;
  }
}
```

See that second server, proxy_pass is     proxy_pass http**s**://iredMailHttp**S**/;

**Comment by lejmr** [comment] 2017-10-07 18:59
I see, so that was not caused by container itself.. Therefore, I am closing this issue. Thank you for feedback!

**Closed by lejmr** 2017-10-07 18:59 UTC
